### PR TITLE
Added Dashlet

### PR DESCRIPTION
**Pull request by vingle**
This relates to https://github.com/systopia/de.systopia.mutualaid/issues/17

Important - this PR still requires work - it doesn't include an install process for adding the Dashlet to the civicrm_dashboard table in the database, and the two links to the two matches reports are hard coded, not dynamic.

image

### CODE REVIEW

**Comment by bjendres** [comment]
Thanks @vingle! 
I created branch [issue/17](https://github.com/systopia/de.systopia.mutualaid/tree/issue/17) for this. I just added an upgrader to install the dashboard, fixed the links, and added translation.

I did not automatically install the dashlet on the user's dashboard, that seemed a little intrusive to me.

@vingle do you want to give it a try before I merge it?

**Comment by vingle** [comment]
Thanks @bjendres! 

I just tried but it didn't create the Dashlet in the dbse. Do I need to trigger an upgrade to get it created? (I just uninstalled/reinstalled)

**Comment by bjendres** [comment]
Did you run the update script on the extension screen? Or was it a new installation?

On 15 May 2020 20:22:48 CEST, Nicol <notifications@github.com> wrote:
>Thanks @bjendres! 
>
>I just tried but it didn't create the Dashlet in the dbse. Do I need to
>trigger an upgrade to get it created? (I just uninstalled/reinstalled) 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/systopia/de.systopia.mutualaid/pull/29#issuecomment-629409548

-- 
SYSTOPIA Organisationsberatung
Peth, Endres, Schuttenberg GbR
Franzstr. 11, 53111 Bonn

Björn Endres
Geschäftsführender Gesellschafter

+49 (0)228 96104990
endres@systopia.de
www.systopia.de

**Comment by vingle** [comment]
> Did you run the update script on the extension screen? Or was it a new installation?

New installation. Just double-checked and the update script works, but uninstalling and reinstalling doesn't add the dashlet. (I hacked this https://github.com/vingle/de.systopia.mutualaid/commit/1ce072ad446202e3cd3f5d35c24a09d2934f20ea - and then it added the row to the table on install)

**Comment by bjendres** [comment]
Sorry, you're right, my bad. I've updated the branch. 

@vingle Could you test again please?

**Comment by vingle** [comment]
@bjendres works great for me - no error if the dashlet is already in the dbse, adds it if it isn't. 

Doesn't remove it from the dbse if uninstalled, but that's an edgecase - and easily overriden by reordering the dashboard.

**Comment by bjendres** [comment]
> Doesn't remove it from the dbse if uninstalled, but that's an edgecase - and easily overriden by reordering the dashboard.

I'm o.k. with that :)

**Pull request merged**
